package de.coldtea.verborum.core.localization

/** Azerbaijani. */
internal object AzerbaijaniStrings : Strings {
    override val back = "Geri"
    override val retry = "Yenidən cəhd et"
    override val cancel = "Ləğv et"
    override val delete = "Sil"
    override val edit = "Redaktə et"
    override val remove = "Çıxar"
    override val offline = "Oflaynsınız. Dəyişikliklər lokal saxlanılır və bağlantı bərpa olunanda sinxronlaşdırılır."
    override val signIn = "Daxil ol"
    override val createAccount = "Hesab yarat"
    override val signInTagline = "Lüğətləriniz, bütün cihazlarınızda."
    override val forum = "Forum"
    override val options = "Parametrlər"
    override val comingSoon = "Tezliklə"
    override val forumFailed = "Forum yüklənə bilmədi."
    override val yourAccount = "Hesabınız"
    override val signOut = "Çıxış"
    override val signingOut = "Çıxış edilir…"
    override val howToUseTheApp = "Tətbiqdən necə istifadə etməli"
    override val appLanguage = "Tətbiq dili"
    override val appLanguageSubtitle = "Verborumun özünün danışdığı dil."
    override val systemLanguage = "Sistem dili"
    override val yourDictionaries = "Lüğətləriniz"
    override val yourDictionariesSubtitle = "Qurduğunuz hər dil cütü bir yerdə."
    override val searchDictionaries = "Lüğətlərdə axtar…"
    override val searchDictionariesAction = "Lüğətlərdə axtar"
    override val clearSearch = "Axtarışı təmizlə"
    override val clear = "Sıfırla"
    override val sortBy = "Sırala"
    override val anyLanguage = "Hamısı"
    override val moreOptions = "Digər seçimlər"
    override val createDictionary = "Lüğət yarat"
    override val noDictionariesMatchSearch = "Axtarışınıza uyğun lüğət yoxdur."
    override val noDictionaryMatchesFilters = "Bu filtrlərə uyğun lüğət yoxdur."
    override val dictionariesFailed = "Lüğətləriniz yüklənə bilmədi."
    override val refreshFailed = "Yenilənmədi. Əvvəl yüklənən göstərilir."
    override val dictionaryDeleteFailed = "Lüğət silinə bilmədi. Siyahınıza qaytarıldı."
    override val dictionary = "Lüğət"
    override val backToDictionaries = "Lüğətlərə qayıt"
    override val test = "Test"
    override val selfPractice = "Sərbəst məşq"
    override val wordList = "Söz siyahısı"
    override val words = "Sözlər"
    override val addWord = "+ Söz əlavə et"
    override val deleteDictionary = "Lüğəti sil"
    override val deleteWord = "Sözü sil"
    override val noWordsYet = "Hələ söz yoxdur. İlkini aşağıda əlavə edin."
    override val dictionaryFailed = "Bu lüğət yüklənə bilmədi."
    override val wordDeleteFailed = "Söz silinə bilmədi. Siyahıya qaytarıldı."
    override val newDictionary = "Yeni lüğət"
    override val editDictionaryTitle = "Lüğəti redaktə et"
    override val createDictionarySubtitle = "Ad verin, dil cütünü seçin və asan süzmək üçün etiketləyin."
    override val dictionaryName = "Lüğətin adı"
    override val dictionaryNameHint = "məs. Alman dilinin əsasları"
    override val fromLanguage = "Mənbə dil"
    override val toLanguage = "Hədəf dil"
    override val select = "Seçin…"
    override val tags = "Etiketlər"
    override val tagsHint = "Lüğətinizi təşkil etmək üçün etiketlər əlavə edin (istəyə bağlı)"
    override val tagSectionLevel = "Səviyyə"
    override val tagSectionTopic = "Mövzu"
    override val tagSectionExam = "İmtahan"
    override val tagSelectorExpanded = "Genişləndirildi"
    override val tagSelectorCollapsed = "Yığcamlaşdırıldı"
    override val tagLevelBasic = "Əsas"
    override val tagLevelIntermediate = "Orta"
    override val tagLevelAdvanced = "Qabaqcıl"
    override val tagTopicFoodDrink = "Yemək və içki"
    override val tagTopicHomeAppliances = "Ev və məişət texnikası"
    override val tagTopicClothing = "Geyim"
    override val tagTopicFamily = "Ailə"
    override val tagTopicDailyRoutine = "Gündəlik rejim"
    override val tagTopicShopping = "Alış-veriş"
    override val tagTopicMoney = "Pul"
    override val tagTopicTravel = "Səyahət"
    override val tagTopicTransport = "Nəqliyyat"
    override val tagTopicCarsParts = "Avtomobillər və hissələr"
    override val tagTopicDirections = "İstiqamətlər"
    override val tagTopicCity = "Şəhər"
    override val tagTopicNatureWeather = "Təbiət və hava"
    override val tagTopicAnimals = "Heyvanlar"
    override val tagTopicPlants = "Bitkilər"
    override val tagTopicBodyHealth = "Bədən və sağlamlıq"
    override val tagTopicMedicine = "Tibb"
    override val tagTopicEmotions = "Duyğular"
    override val tagTopicWorkOffice = "İş və ofis"
    override val tagTopicBusiness = "Biznes"
    override val tagTopicEducation = "Təhsil"
    override val tagTopicItTechnology = "İT və texnologiya"
    override val tagTopicLaw = "Hüquq"
    override val tagTopicScience = "Elm"
    override val tagTopicSports = "İdman"
    override val tagTopicMusic = "Musiqi"
    override val tagTopicArtFilm = "İncəsənət və kino"
    override val tagTopicCultureHolidays = "Mədəniyyət və bayramlar"
    override val tagTopicNewsPolitics = "Xəbərlər və siyasət"
    override val tagTopicFoodService = "İaşə xidməti"
    override val saveChanges = "Dəyişiklikləri yadda saxla"
    override val saving = "Yadda saxlanılır…"
    override val dictionarySaveFailed = "Lüğət yadda saxlanıla bilmədi."
    override val dictionaryLoadFailed = "Lüğət yüklənə bilmədi."
    override val newWord = "Yeni söz"
    override val editWordTitle = "Sözü redaktə et"
    override val addWordTitle = "Söz əlavə et"
    override val saveWord = "Sözü yadda saxla"
    override val wordType = "Söz növü"
    override val typeOfWord = "Sözün növü"
    override val word = "Söz"
    override val gender = "Cins"
    override val addAnotherMeaning = "+ Başqa məna əlavə et"
    override val wordSaveFailed = "Söz yadda saxlanıla bilmədi."
    override val wordLoadFailed = "Bu söz yüklənə bilmədi."
    override val wordFirst = "Əvvəl söz"
    override val translationFirst = "Əvvəl tərcümə"
    override val switchSides = "Tərəfləri dəyiş"
    override val correct = "Doğru"
    override val wrong = "Yanlış"
    override val practiceFailed = "Bu məşq sessiyası yüklənə bilmədi."
    override val exitTest = "Testdən çıx"
    override val testComplete = "Test tamamlandı"
    override val checkAnswer = "Cavabı yoxla"
    override val nextQuestion = "Növbəti sual"
    override val testFailed = "Bu test yüklənə bilmədi."
    override val answerSaveFailed = "Cavab yadda saxlanıla bilmədi."
    override val wellDone = "Afərin!"
    override val keepPracticing = "Məşqə davam edin"
    override val passedMessage = "Bu sözlərə yaxşı bələdsiniz. Əla iş!"
    override val failedMessage = "Sözləri nəzərdən keçirin və nəticənizi yaxşılaşdırmaq üçün yenidən cəhd edin."
    override val incorrect = "Yanlış"
    override val backToDictionary = "Lüğətə qayıt"
    override val tryAgain = "Yenidən cəhd et"
    override val onboardingWelcomeTitle = "Verboruma xoş gəlmisiniz"
    override val onboardingLibraryTitle = "Kitabxananızı qurun"
    override val onboardingTestTitle = "Özünüzü sınayın"
    override val onboardingPracticeSwipeTitle = "Sürüşdürərək məşq edin"
    override val onboardingPracticeFlipTitle = "Kartı çevirərək məşq edin"
    override val iAmDone = "Bitirdim"
    override val closeKeyboard = "Klaviaturanı bağla"
    override val space = "boşluq"
    override val shift = "Shift"
    override val symbols = "Simvollar"
    override val backspace = "Geri sil"
    override val nextField = "Növbəti sahə"
    override val keyboardUnavailable = "Klaviatura yoxdur — əvvəlcə dil seçin"
    override val bopomofoNote = "Bopomofo — simvollar üçün sisteminizin daxiletmə üsulundan istifadə edin."
    override val pinyinNote = "Yalnız pinyin — simvollar üçün sisteminizin daxiletmə üsulundan istifadə edin."
    override val noun = "isim"
    override val verb = "fel"
    override val adjective = "sifət"
    override val adverb = "zərf"
    override val other = "digər"
    override val freeText = "sərbəst mətn"
    override val preposition = "qoşma"
    override val pronoun = "əvəzlik"
    override val numeral = "say"
    override val conjunction = "bağlayıcı"
    override val interjection = "nida"
    override val article = "artikl"
    override val reading = "Oxunuş"
    override val plural = "Cəm"
    override val feminine = "Qadın cinsi"
    override val comparative = "Müqayisə"
    override val superlative = "Üstünlük"
    override val present = "İndiki zaman"
    override val past = "Keçmiş zaman"
    override val pastForm = "Keçmiş forma"
    override val participle = "Feli sifət"
    override val auxiliary = "Köməkçi fel"
    override val aspect = "Görünüş"
    override val root = "Kök"
    override val stem = "Əsas"
    override val measure = "Say sözü"
    override val wordClass = "Sinif"
    override val polite = "Nəzakətli forma"
    override val masculine = "kişi cinsi"
    override val neuter = "orta cins"
    override val common = "ümumi"
    override val sortNameAsc = "Ad A–Z"
    override val sortNameDesc = "Ad Z–A"
    override val sortNewest = "Əvvəl ən yenilər"
    override val sortOldest = "Əvvəl ən köhnələr"

    override fun deleteDictionaryWarning(name: String) = "“$name” və bütün sözləri silinəcək."
    override fun wordCount(count: Int) = "$count söz"
    override fun meaningNumber(index: Int) = "$index. məna"
    override fun backTo(name: String) = "$name lüğətinə qayıt"
    override fun questionProgress(index: Int, total: Int) = "Sual $index / $total"
    override fun askMeaning(word: String) = "“$word” nə deməkdir?"
    override fun askForm(word: String) = "“$word” nədir?"
    override fun correctAnswerWas(answer: String) = "Tam deyil — doğru cavab “$answer”."
    override fun notEnoughWords(required: Int) =
        "Test üçün aralarından seçiləcək ən azı $required fərqli söz lazımdır."
    override fun scoreOf(correct: Int, total: Int) = "$total sualdan $correct"
    override fun showKeyboard(language: String) = "$language klaviaturasını göstər"
    override fun hideKeyboard(language: String) = "$language klaviaturasını gizlət"

    override fun languageName(code: String): String = when (code.lowercase()) {
        "en" -> "İngiliscə"
        "de" -> "Almanca"
        "fr" -> "Fransızca"
        "es" -> "İspanca"
        "it" -> "İtalyanca"
        "pt" -> "Portuqalca"
        "nl" -> "Niderlandca"
        "lt" -> "Litvaca"
        "tr" -> "Türkcə"
        "az" -> "Azərbaycanca"
        "pl" -> "Polyakca"
        "uk" -> "Ukraynaca"
        "ru" -> "Rusca"
        "el" -> "Yunanca"
        "ar" -> "Ərəbcə"
        "fa" -> "Farsca"
        "ja" -> "Yaponca"
        "zh" -> "Çincə"
        "ko" -> "Koreyaca"
        else -> code
    }

    override fun tagLabel(code: String): String? = when (code) {
        "basic" -> "Əsas"
        "intermediate" -> "Orta"
        "advanced" -> "İrəli"
        "food_drink" -> "Yemək və içki"
        "home_appliances" -> "Ev və məişət texnikası"
        "clothing" -> "Geyim"
        "family" -> "Ailə"
        "daily_routine" -> "Gündəlik həyat"
        "shopping" -> "Alış-veriş"
        "money" -> "Pul"
        "travel" -> "Səyahət"
        "transport" -> "Nəqliyyat"
        "cars_parts" -> "Avtomobillər və hissələr"
        "directions" -> "İstiqamətlər"
        "city" -> "Şəhər"
        "nature_weather" -> "Təbiət və hava"
        "animals" -> "Heyvanlar"
        "plants" -> "Bitkilər"
        "body_health" -> "Bədən və sağlamlıq"
        "medicine" -> "Tibb"
        "emotions" -> "Emosiyalar"
        "work_office" -> "İş və ofis"
        "business" -> "Biznes"
        "education" -> "Təhsil"
        "it_technology" -> "İT və texnologiya"
        "law" -> "Hüquq"
        "science" -> "Elm"
        "sports" -> "İdman"
        "music" -> "Musiqi"
        "art_film" -> "İncəsənət və kino"
        "culture_holidays" -> "Mədəniyyət və bayramlar"
        "news_politics" -> "Xəbər və siyasət"
        "food_service" -> "İaşə"
        else -> null
    }

    override val onboardingWelcomeBody = "Şəxsi lüğət kitabxananız. Lüğətlər qurun, sözlər toplayın və yadda saxlayın."
    override val onboardingLibraryBody = "İstənilən dil cütü üçün lüğət yaradın, sonra sözləri qrammatikası ilə birlikdə əlavə edin — artikllar, cəm formaları, fel formaları və daha çoxu."
    override val onboardingTestBody = "Sözlərinizlə çoxseçimli testlər keçin. Daxil etdiyiniz hər forma öz sualını alır və doğru cavablar sözün səviyyəsini qaldırır."
    override val onboardingPracticeSwipeBody = "Məşq zamanı karta toxunub tərcüməni görün, bilirdinizsə sağa, bilmirdinizsə sola sürüşdürün — hər halda səviyyə dəyişir."
    override val onboardingPracticeFlipBody = "Məşq zamanı karta klikləyib çevirin. Sonra doğru və ya yanlış işarələyin — hər halda sözün səviyyəsi dəyişir."
}
