package de.coldtea.verborum.core.localization

/** Simplified Chinese. */
internal object ChineseStrings : Strings {
    override val back = "返回"
    override val retry = "重试"
    override val cancel = "取消"
    override val delete = "删除"
    override val edit = "编辑"
    override val remove = "移除"
    override val offline = "你已离线。更改会保存在本地，重新连接后同步。"
    override val signIn = "登录"
    override val createAccount = "创建账户"
    override val signInTagline = "你的词典，随处可用。"
    override val forum = "论坛"
    override val options = "设置"
    override val comingSoon = "敬请期待"
    override val forumFailed = "无法加载论坛。"
    override val yourAccount = "你的账户"
    override val signOut = "退出登录"
    override val signingOut = "正在退出…"
    override val howToUseTheApp = "如何使用本应用"
    override val appLanguage = "应用语言"
    override val appLanguageSubtitle = "Verborum 自身使用的语言。"
    override val systemLanguage = "系统语言"
    override val yourDictionaries = "你的词典"
    override val yourDictionariesSubtitle = "你正在建立的每一组语言对，都在这里。"
    override val searchDictionaries = "搜索词典…"
    override val searchDictionariesAction = "搜索词典"
    override val clearSearch = "清除搜索"
    override val clear = "重置"
    override val sortBy = "排序方式"
    override val anyLanguage = "全部"
    override val moreOptions = "更多选项"
    override val createDictionary = "创建词典"
    override val noDictionariesMatchSearch = "没有词典符合你的搜索。"
    override val noDictionaryMatchesFilters = "没有词典符合这些筛选条件。"
    override val dictionariesFailed = "无法加载你的词典。"
    override val refreshFailed = "刷新失败，显示的是先前加载的内容。"
    override val dictionaryDeleteFailed = "无法删除该词典，已放回你的列表。"
    override val dictionary = "词典"
    override val backToDictionaries = "返回词典列表"
    override val test = "测验"
    override val selfPractice = "自主练习"
    override val wordList = "单词列表"
    override val words = "单词"
    override val addWord = "+ 添加单词"
    override val deleteDictionary = "删除词典"
    override val deleteWord = "删除单词"
    override val noWordsYet = "还没有单词，请在下方添加第一个。"
    override val dictionaryFailed = "无法加载此词典。"
    override val wordDeleteFailed = "无法删除该单词，已放回列表。"
    override val newDictionary = "新建词典"
    override val editDictionaryTitle = "编辑词典"
    override val createDictionarySubtitle = "取个名字，选择语言对，再加上标签便于筛选。"
    override val dictionaryName = "词典名称"
    override val dictionaryNameHint = "例如：德语基础"
    override val fromLanguage = "源语言"
    override val toLanguage = "目标语言"
    override val select = "请选择…"
    override val tags = "标签"
    override val tagSectionLevel = "等级"
    override val tagSectionTopic = "主题"
    override val tagSectionExam = "考试"
    override val tagSelectorExpanded = "已展开"
    override val tagSelectorCollapsed = "已折叠"
    override val tagLevelBasic = "初级"
    override val tagLevelIntermediate = "中级"
    override val tagLevelAdvanced = "高级"
    override val tagTopicFoodDrink = "食物与饮料"
    override val tagTopicHomeAppliances = "家居与电器"
    override val tagTopicClothing = "服装"
    override val tagTopicFamily = "家庭"
    override val tagTopicDailyRoutine = "日常生活"
    override val tagTopicShopping = "购物"
    override val tagTopicMoney = "金钱"
    override val tagTopicTravel = "旅行"
    override val tagTopicTransport = "交通"
    override val tagTopicCarsParts = "汽车与零件"
    override val tagTopicDirections = "方向指引"
    override val tagTopicCity = "城市"
    override val tagTopicNatureWeather = "自然与天气"
    override val tagTopicAnimals = "动物"
    override val tagTopicPlants = "植物"
    override val tagTopicBodyHealth = "身体与健康"
    override val tagTopicMedicine = "医学"
    override val tagTopicEmotions = "情绪"
    override val tagTopicWorkOffice = "工作与办公室"
    override val tagTopicBusiness = "商业"
    override val tagTopicEducation = "教育"
    override val tagTopicItTechnology = "信息技术"
    override val tagTopicLaw = "法律"
    override val tagTopicScience = "科学"
    override val tagTopicSports = "运动"
    override val tagTopicMusic = "音乐"
    override val tagTopicArtFilm = "艺术与电影"
    override val tagTopicCultureHolidays = "文化与节日"
    override val tagTopicNewsPolitics = "新闻与政治"
    override val tagTopicFoodService = "餐饮服务"
    override val saveChanges = "保存更改"
    override val saving = "正在保存…"
    override val dictionarySaveFailed = "无法保存词典。"
    override val dictionaryLoadFailed = "无法加载词典。"
    override val newWord = "新建单词"
    override val editWordTitle = "编辑单词"
    override val addWordTitle = "添加单词"
    override val saveWord = "保存单词"
    override val wordType = "词性"
    override val typeOfWord = "单词类型"
    override val word = "单词"
    override val gender = "性"
    override val addAnotherMeaning = "+ 添加另一个含义"
    override val wordSaveFailed = "无法保存单词。"
    override val wordLoadFailed = "无法加载此单词。"
    override val wordFirst = "先看单词"
    override val translationFirst = "先看翻译"
    override val switchSides = "交换两面"
    override val correct = "正确"
    override val wrong = "错误"
    override val practiceFailed = "无法加载此练习。"
    override val exitTest = "退出测验"
    override val testComplete = "测验完成"
    override val checkAnswer = "检查答案"
    override val nextQuestion = "下一题"
    override val testFailed = "无法加载此测验。"
    override val answerSaveFailed = "无法保存答案。"
    override val wellDone = "做得好！"
    override val keepPracticing = "继续练习"
    override val passedMessage = "你已经很好地掌握了这些单词，太棒了！"
    override val failedMessage = "复习这些单词后再试一次，以提高成绩。"
    override val incorrect = "错误"
    override val backToDictionary = "返回词典"
    override val tryAgain = "再试一次"
    override val onboardingWelcomeTitle = "欢迎使用 Verborum"
    override val onboardingLibraryTitle = "建立你的词库"
    override val onboardingTestTitle = "测试自己"
    override val onboardingPracticeSwipeTitle = "滑动练习"
    override val onboardingPracticeFlipTitle = "翻卡片练习"
    override val iAmDone = "我知道了"
    override val closeKeyboard = "关闭键盘"
    override val space = "空格"
    override val shift = "上档"
    override val symbols = "符号"
    override val backspace = "退格"
    override val nextField = "下一个输入框"
    override val keyboardUnavailable = "没有键盘 — 请先选择语言"
    override val bopomofoNote = "注音 — 请使用系统输入法转换为汉字。"
    override val pinyinNote = "仅拼音 — 请使用系统输入法输入汉字。"
    override val noun = "名词"
    override val verb = "动词"
    override val adjective = "形容词"
    override val adverb = "副词"
    override val other = "其他"
    override val freeText = "自由文本"
    override val preposition = "介词"
    override val pronoun = "代词"
    override val numeral = "数词"
    override val conjunction = "连词"
    override val interjection = "叹词"
    override val article = "冠词"
    override val reading = "读音"
    override val plural = "复数"
    override val feminine = "阴性"
    override val comparative = "比较级"
    override val superlative = "最高级"
    override val present = "现在时"
    override val past = "过去时"
    override val pastForm = "过去形式"
    override val participle = "分词"
    override val auxiliary = "助动词"
    override val aspect = "体"
    override val root = "词根"
    override val stem = "词干"
    override val measure = "量词"
    override val wordClass = "类别"
    override val polite = "敬语形式"
    override val masculine = "阳性"
    override val neuter = "中性"
    override val common = "通性"
    override val sortNameAsc = "名称 A–Z"
    override val sortNameDesc = "名称 Z–A"
    override val sortNewest = "最新优先"
    override val sortOldest = "最早优先"

    override fun deleteDictionaryWarning(name: String) = "“$name”及其全部单词都将被删除。"
    override fun wordCount(count: Int) = "$count 个单词"
    override fun meaningNumber(index: Int) = "含义 $index"
    override fun backTo(name: String) = "返回 $name"
    override fun questionProgress(index: Int, total: Int) = "第 $index 题，共 $total 题"
    override fun askMeaning(word: String) = "“$word”是什么意思？"
    override fun askForm(word: String) = "“$word”是什么？"
    override fun correctAnswerWas(answer: String) = "差一点 — 答案是“$answer”。"
    override fun notEnoughWords(required: Int) = "测验至少需要 $required 个不同的单词作为选项。"
    override fun scoreOf(correct: Int, total: Int) = "$total 题中答对 $correct 题"
    override fun showKeyboard(language: String) = "显示${language}键盘"
    override fun hideKeyboard(language: String) = "隐藏${language}键盘"

    override fun languageName(code: String): String = when (code.lowercase()) {
        "en" -> "英语"
        "de" -> "德语"
        "fr" -> "法语"
        "es" -> "西班牙语"
        "it" -> "意大利语"
        "pt" -> "葡萄牙语"
        "nl" -> "荷兰语"
        "lt" -> "立陶宛语"
        "tr" -> "土耳其语"
        "az" -> "阿塞拜疆语"
        "pl" -> "波兰语"
        "uk" -> "乌克兰语"
        "ru" -> "俄语"
        "el" -> "希腊语"
        "ar" -> "阿拉伯语"
        "fa" -> "波斯语"
        "ja" -> "日语"
        "zh" -> "中文"
        "ko" -> "韩语"
        else -> code
    }

    override fun tagLabel(code: String): String? = when (code) {
        "basic" -> "基础"
        "intermediate" -> "中级"
        "advanced" -> "高级"
        "food_drink" -> "饮食"
        "home_appliances" -> "家居与电器"
        "clothing" -> "服装"
        "family" -> "家庭"
        "daily_routine" -> "日常生活"
        "shopping" -> "购物"
        "money" -> "金钱"
        "travel" -> "旅行"
        "transport" -> "交通"
        "cars_parts" -> "汽车与配件"
        "directions" -> "问路"
        "city" -> "城市"
        "nature_weather" -> "自然与天气"
        "animals" -> "动物"
        "plants" -> "植物"
        "body_health" -> "身体与健康"
        "medicine" -> "医学"
        "emotions" -> "情绪"
        "work_office" -> "工作与办公"
        "business" -> "商务"
        "education" -> "教育"
        "it_technology" -> "信息技术"
        "law" -> "法律"
        "science" -> "科学"
        "sports" -> "体育"
        "music" -> "音乐"
        "art_film" -> "艺术与电影"
        "culture_holidays" -> "文化与节日"
        "news_politics" -> "新闻与政治"
        "food_service" -> "餐饮服务"
        else -> null
    }

    override val onboardingWelcomeBody = "你的个人词汇库。建立词典，收集单词，并把它们记牢。"
    override val onboardingLibraryBody = "为任意语言对创建词典，然后连同语法一起添加单词——冠词、复数、动词变位等等。"
    override val onboardingTestBody = "用你的单词做选择题测验。你录入的每个形式都会成为一道题，答对可以提升单词的等级。"
    override val onboardingPracticeSwipeBody = "自主练习时点按卡片查看翻译，记得就向右滑，不记得就向左滑——无论哪种，等级都会变化。"
    override val onboardingPracticeFlipBody = "自主练习时点击卡片将其翻转，然后标记正确或错误——无论哪种，单词的等级都会变化。"
}
