package de.coldtea.verborum.core.localization

/** French. */
internal object FrenchStrings : Strings {
    override val back = "Retour"
    override val retry = "Réessayer"
    override val cancel = "Annuler"
    override val delete = "Supprimer"
    override val edit = "Modifier"
    override val remove = "Retirer"
    override val offline = "Vous êtes hors ligne. Les modifications sont enregistrées localement et synchronisées à la reconnexion."
    override val signIn = "Se connecter"
    override val createAccount = "Créer un compte"
    override val signInTagline = "Vos dictionnaires, sur tous vos appareils."
    override val forum = "Forum"
    override val options = "Options"
    override val comingSoon = "Bientôt disponible"
    override val forumFailed = "Le forum n'a pas pu être chargé."
    override val yourAccount = "Votre compte"
    override val signOut = "Se déconnecter"
    override val signingOut = "Déconnexion…"
    override val howToUseTheApp = "Comment utiliser l'application"
    override val appLanguage = "Langue de l'application"
    override val appLanguageSubtitle = "La langue que parle Verborum lui-même."
    override val systemLanguage = "Langue du système"
    override val yourDictionaries = "Vos dictionnaires"
    override val yourDictionariesSubtitle = "Chaque paire de langues que vous construisez, au même endroit."
    override val searchDictionaries = "Rechercher des dictionnaires…"
    override val searchDictionariesAction = "Rechercher des dictionnaires"
    override val clearSearch = "Effacer la recherche"
    override val clear = "Réinitialiser"
    override val sortBy = "Trier par"
    override val anyLanguage = "Toutes"
    override val moreOptions = "Plus d'options"
    override val createDictionary = "Créer un dictionnaire"
    override val noDictionariesMatchSearch = "Aucun dictionnaire ne correspond à votre recherche."
    override val noDictionaryMatchesFilters = "Aucun dictionnaire ne correspond à ces filtres."
    override val dictionariesFailed = "Vos dictionnaires n'ont pas pu être chargés."
    override val refreshFailed = "Actualisation impossible. Voici le dernier état chargé."
    override val dictionaryDeleteFailed = "Le dictionnaire n'a pas pu être supprimé. Il est de retour dans votre liste."
    override val dictionary = "Dictionnaire"
    override val backToDictionaries = "Retour aux dictionnaires"
    override val test = "Test"
    override val selfPractice = "Entraînement libre"
    override val wordList = "Liste de mots"
    override val words = "Mots"
    override val addWord = "+ Ajouter un mot"
    override val deleteDictionary = "Supprimer le dictionnaire"
    override val deleteWord = "Supprimer le mot"
    override val noWordsYet = "Aucun mot pour l'instant. Ajoutez le premier ci-dessous."
    override val dictionaryFailed = "Ce dictionnaire n'a pas pu être chargé."
    override val wordDeleteFailed = "Le mot n'a pas pu être supprimé. Il est de retour dans la liste."
    override val newDictionary = "Nouveau dictionnaire"
    override val editDictionaryTitle = "Modifier le dictionnaire"
    override val createDictionarySubtitle = "Donnez-lui un nom, choisissez une paire de langues et ajoutez des étiquettes pour filtrer."
    override val dictionaryName = "Nom du dictionnaire"
    override val dictionaryNameHint = "ex. Allemand pour débutants"
    override val fromLanguage = "Langue source"
    override val toLanguage = "Langue cible"
    override val select = "Choisir…"
    override val tags = "Étiquettes"
    override val tagsHint = "Ajoutez des étiquettes pour organiser votre dictionnaire (facultatif)"
    override val tagSectionLevel = "Niveau"
    override val tagSectionTopic = "Thème"
    override val tagSectionExam = "Examen"
    override val tagSelectorExpanded = "Développé"
    override val tagSelectorCollapsed = "Réduit"
    override val tagLevelBasic = "Débutant"
    override val tagLevelIntermediate = "Intermédiaire"
    override val tagLevelAdvanced = "Avancé"
    override val tagTopicFoodDrink = "Nourriture et boissons"
    override val tagTopicHomeAppliances = "Maison et électroménager"
    override val tagTopicClothing = "Vêtements"
    override val tagTopicFamily = "Famille"
    override val tagTopicDailyRoutine = "Routine quotidienne"
    override val tagTopicShopping = "Achats"
    override val tagTopicMoney = "Argent"
    override val tagTopicTravel = "Voyages"
    override val tagTopicTransport = "Transport"
    override val tagTopicCarsParts = "Voitures et pièces"
    override val tagTopicDirections = "Directions"
    override val tagTopicCity = "Ville"
    override val tagTopicNatureWeather = "Nature et météo"
    override val tagTopicAnimals = "Animaux"
    override val tagTopicPlants = "Plantes"
    override val tagTopicBodyHealth = "Corps et santé"
    override val tagTopicMedicine = "Médecine"
    override val tagTopicEmotions = "Émotions"
    override val tagTopicWorkOffice = "Travail et bureau"
    override val tagTopicBusiness = "Affaires"
    override val tagTopicEducation = "Éducation"
    override val tagTopicItTechnology = "Informatique et technologie"
    override val tagTopicLaw = "Droit"
    override val tagTopicScience = "Science"
    override val tagTopicSports = "Sports"
    override val tagTopicMusic = "Musique"
    override val tagTopicArtFilm = "Art et cinéma"
    override val tagTopicCultureHolidays = "Culture et fêtes"
    override val tagTopicNewsPolitics = "Actualité et politique"
    override val tagTopicFoodService = "Restauration"
    override val saveChanges = "Enregistrer les modifications"
    override val saving = "Enregistrement…"
    override val dictionarySaveFailed = "Le dictionnaire n'a pas pu être enregistré."
    override val dictionaryLoadFailed = "Le dictionnaire n'a pas pu être chargé."
    override val newWord = "Nouveau mot"
    override val editWordTitle = "Modifier le mot"
    override val addWordTitle = "Ajouter un mot"
    override val saveWord = "Enregistrer le mot"
    override val wordType = "Nature du mot"
    override val typeOfWord = "Type de mot"
    override val word = "Mot"
    override val gender = "Genre"
    override val addAnotherMeaning = "+ Ajouter un autre sens"
    override val wordSaveFailed = "Le mot n'a pas pu être enregistré."
    override val wordLoadFailed = "Ce mot n'a pas pu être chargé."
    override val wordFirst = "Mot d'abord"
    override val translationFirst = "Traduction d'abord"
    override val switchSides = "Inverser les côtés"
    override val correct = "Correct"
    override val wrong = "Incorrect"
    override val practiceFailed = "Cette session d'entraînement n'a pas pu être chargée."
    override val exitTest = "Quitter le test"
    override val testComplete = "Test terminé"
    override val checkAnswer = "Vérifier la réponse"
    override val nextQuestion = "Question suivante"
    override val testFailed = "Ce test n'a pas pu être chargé."
    override val answerSaveFailed = "La réponse n'a pas pu être enregistrée."
    override val wellDone = "Bravo !"
    override val keepPracticing = "Continuez à vous entraîner"
    override val passedMessage = "Vous maîtrisez bien ces mots. Excellent travail !"
    override val failedMessage = "Revoyez les mots et réessayez pour améliorer votre score."
    override val incorrect = "Incorrect"
    override val backToDictionary = "Retour au dictionnaire"
    override val tryAgain = "Réessayer"
    override val onboardingWelcomeTitle = "Bienvenue dans Verborum"
    override val onboardingLibraryTitle = "Constituez votre bibliothèque"
    override val onboardingTestTitle = "Testez-vous"
    override val onboardingPracticeSwipeTitle = "Entraînez-vous d'un glissement"
    override val onboardingPracticeFlipTitle = "Entraînez-vous en retournant"
    override val iAmDone = "J'ai terminé"
    override val closeKeyboard = "Fermer le clavier"
    override val space = "espace"
    override val shift = "Maj"
    override val symbols = "Symboles"
    override val backspace = "Retour arrière"
    override val nextField = "Champ suivant"
    override val keyboardUnavailable = "Aucun clavier — choisissez d'abord une langue"
    override val bopomofoNote = "Bopomofo — utilisez la méthode de saisie de votre système pour les caractères."
    override val pinyinNote = "Pinyin uniquement — utilisez la méthode de saisie de votre système pour les caractères."
    override val noun = "nom"
    override val verb = "verbe"
    override val adjective = "adjectif"
    override val adverb = "adverbe"
    override val other = "autre"
    override val freeText = "texte libre"
    override val preposition = "préposition"
    override val pronoun = "pronom"
    override val numeral = "numéral"
    override val conjunction = "conjonction"
    override val interjection = "interjection"
    override val article = "article"
    override val reading = "Lecture"
    override val plural = "Pluriel"
    override val feminine = "Féminin"
    override val comparative = "Comparatif"
    override val superlative = "Superlatif"
    override val present = "Présent"
    override val past = "Passé"
    override val pastForm = "Forme passée"
    override val participle = "Participe"
    override val auxiliary = "Auxiliaire"
    override val aspect = "Aspect"
    override val root = "Racine"
    override val stem = "Radical"
    override val measure = "Classificateur"
    override val wordClass = "Classe"
    override val polite = "Forme polie"
    override val masculine = "masculin"
    override val neuter = "neutre"
    override val common = "commun"
    override val sortNameAsc = "Nom A–Z"
    override val sortNameDesc = "Nom Z–A"
    override val sortNewest = "Plus récents d'abord"
    override val sortOldest = "Plus anciens d'abord"

    override fun deleteDictionaryWarning(name: String) = "« $name » et tous ses mots seront supprimés."
    override fun wordCount(count: Int) = if (count == 1) "1 mot" else "$count mots"
    override fun meaningNumber(index: Int) = "Sens $index"
    override fun backTo(name: String) = "Retour à $name"
    override fun questionProgress(index: Int, total: Int) = "Question $index sur $total"
    override fun askMeaning(word: String) = "Que signifie « $word » ?"
    override fun askForm(word: String) = "Qu'est-ce que « $word » ?"
    override fun correctAnswerWas(answer: String) = "Pas tout à fait — la réponse est « $answer »."
    override fun notEnoughWords(required: Int) =
        "Un test a besoin d'au moins $required mots différents parmi lesquels choisir."
    override fun scoreOf(correct: Int, total: Int) = "$correct sur $total"
    override fun showKeyboard(language: String) = "Afficher le clavier $language"
    override fun hideKeyboard(language: String) = "Masquer le clavier $language"

    override fun languageName(code: String): String = when (code.lowercase()) {
        "en" -> "Anglais"
        "de" -> "Allemand"
        "fr" -> "Français"
        "es" -> "Espagnol"
        "it" -> "Italien"
        "pt" -> "Portugais"
        "nl" -> "Néerlandais"
        "lt" -> "Lituanien"
        "tr" -> "Turc"
        "az" -> "Azerbaïdjanais"
        "pl" -> "Polonais"
        "uk" -> "Ukrainien"
        "ru" -> "Russe"
        "el" -> "Grec"
        "ar" -> "Arabe"
        "fa" -> "Persan"
        "ja" -> "Japonais"
        "zh" -> "Chinois"
        "ko" -> "Coréen"
        else -> code
    }

    override fun tagLabel(code: String): String? = when (code) {
        "basic" -> "Bases"
        "intermediate" -> "Intermédiaire"
        "advanced" -> "Avancé"
        "food_drink" -> "Nourriture & boissons"
        "home_appliances" -> "Maison & appareils"
        "clothing" -> "Vêtements"
        "family" -> "Famille"
        "daily_routine" -> "Routine quotidienne"
        "shopping" -> "Achats"
        "money" -> "Argent"
        "travel" -> "Voyage"
        "transport" -> "Transports"
        "cars_parts" -> "Voitures & pièces"
        "directions" -> "Directions"
        "city" -> "Ville"
        "nature_weather" -> "Nature & météo"
        "animals" -> "Animaux"
        "plants" -> "Plantes"
        "body_health" -> "Corps & santé"
        "medicine" -> "Médecine"
        "emotions" -> "Émotions"
        "work_office" -> "Travail & bureau"
        "business" -> "Affaires"
        "education" -> "Éducation"
        "it_technology" -> "Informatique & technologie"
        "law" -> "Droit"
        "science" -> "Science"
        "sports" -> "Sports"
        "music" -> "Musique"
        "art_film" -> "Art & cinéma"
        "culture_holidays" -> "Culture & fêtes"
        "news_politics" -> "Actualité & politique"
        "food_service" -> "Restauration"
        else -> null
    }

    override val onboardingWelcomeBody = "Votre bibliothèque de vocabulaire. Créez des dictionnaires, collectez des mots et retenez-les."
    override val onboardingLibraryBody = "Créez un dictionnaire pour n'importe quelle paire de langues, puis ajoutez des mots avec leur grammaire — articles, pluriels, formes verbales et plus."
    override val onboardingTestBody = "Passez des tests à choix multiples. Chaque forme saisie devient une question, et les bonnes réponses font monter le niveau d'un mot."
    override val onboardingPracticeSwipeBody = "En entraînement, touchez une carte pour voir la traduction, puis glissez à droite si vous saviez, à gauche sinon — dans les deux cas le niveau bouge."
    override val onboardingPracticeFlipBody = "En entraînement, cliquez sur une carte pour la retourner. Marquez-la ensuite correcte ou incorrecte — dans les deux cas le niveau du mot bouge."
}
