package de.coldtea.verborum.core.localization

/** German. Overrides every key; anything added to [Strings] later falls back to English until translated. */
internal object GermanStrings : Strings {
    override val back = "Zurück"
    override val retry = "Erneut versuchen"
    override val cancel = "Abbrechen"
    override val delete = "Löschen"
    override val edit = "Bearbeiten"
    override val remove = "Entfernen"
    override val offline =
        "Du bist offline. Änderungen werden lokal gespeichert und synchronisiert, sobald du wieder verbunden bist."

    override val signIn = "Anmelden"
    override val createAccount = "Konto erstellen"
    override val signInTagline = "Deine Wörterbücher, auf jedem Gerät."

    override val forum = "Forum"
    override val options = "Einstellungen"
    override val comingSoon = "Demnächst"
    override val forumFailed = "Das Forum konnte nicht geladen werden."

    override val yourAccount = "Dein Konto"
    override val signOut = "Abmelden"
    override val signingOut = "Wird abgemeldet…"
    override val howToUseTheApp = "So funktioniert die App"
    override val appLanguage = "App-Sprache"
    override val appLanguageSubtitle = "Die Sprache, in der Verborum selbst spricht."
    override val systemLanguage = "Systemsprache"

    override val yourDictionaries = "Deine Wörterbücher"
    override val yourDictionariesSubtitle = "Jedes Sprachpaar, an dem du arbeitest, an einem Ort."
    override val searchDictionaries = "Wörterbücher suchen…"
    override val searchDictionariesAction = "Wörterbücher suchen"
    override val clearSearch = "Suche löschen"
    override val clear = "Zurücksetzen"
    override val sortBy = "Sortieren nach"
    override val anyLanguage = "Alle"
    override val moreOptions = "Weitere Optionen"
    override val createDictionary = "Wörterbuch erstellen"
    override val noDictionariesMatchSearch = "Keine Wörterbücher passen zu deiner Suche."
    override val noDictionaryMatchesFilters = "Kein Wörterbuch passt zu diesen Filtern."
    override val dictionariesFailed = "Deine Wörterbücher konnten nicht geladen werden."
    override val refreshFailed = "Aktualisieren fehlgeschlagen. Angezeigt wird der zuletzt geladene Stand."
    override val dictionaryDeleteFailed =
        "Das Wörterbuch konnte nicht gelöscht werden. Es ist wieder in deiner Liste."

    override val dictionary = "Wörterbuch"
    override val backToDictionaries = "Zurück zu den Wörterbüchern"
    override val test = "Test"
    override val selfPractice = "Selbstübung"
    override val wordList = "Wortliste"
    override val words = "Wörter"
    override val addWord = "+ Wort hinzufügen"
    override val deleteDictionary = "Wörterbuch löschen"
    override val deleteWord = "Wort löschen"
    override val noWordsYet = "Noch keine Wörter. Füge unten das erste hinzu."
    override val dictionaryFailed = "Dieses Wörterbuch konnte nicht geladen werden."
    override val wordDeleteFailed = "Das Wort konnte nicht gelöscht werden. Es ist wieder in der Liste."
    override fun deleteDictionaryWarning(name: String) = "„${name}“ und alle seine Wörter werden gelöscht."
    override fun wordCount(count: Int) = if (count == 1) "1 Wort" else "$count Wörter"

    override val newDictionary = "Neues Wörterbuch"
    override val editDictionaryTitle = "Wörterbuch bearbeiten"
    override val createDictionarySubtitle =
        "Gib ihm einen Namen, wähle ein Sprachpaar und vergib Schlagwörter zum Filtern."
    override val dictionaryName = "Name des Wörterbuchs"
    override val dictionaryNameHint = "z. B. Deutsch für Anfänger"
    override val fromLanguage = "Ausgangssprache"
    override val toLanguage = "Zielsprache"
    override val select = "Auswählen…"
    override val tags = "Schlagwörter"
    override val saveChanges = "Änderungen speichern"
    override val saving = "Wird gespeichert…"
    override val dictionarySaveFailed = "Das Wörterbuch konnte nicht gespeichert werden."
    override val dictionaryLoadFailed = "Das Wörterbuch konnte nicht geladen werden."

    override val newWord = "Neues Wort"
    override val editWordTitle = "Wort bearbeiten"
    override val addWordTitle = "Wort hinzufügen"
    override val saveWord = "Wort speichern"
    override val wordType = "Wortart"
    override val typeOfWord = "Art des Wortes"
    override val word = "Wort"
    override val gender = "Genus"
    override val addAnotherMeaning = "+ Weitere Bedeutung"
    override val wordSaveFailed = "Das Wort konnte nicht gespeichert werden."
    override val wordLoadFailed = "Dieses Wort konnte nicht geladen werden."
    override fun meaningNumber(index: Int) = "Bedeutung $index"
    override fun backTo(name: String) = "Zurück zu $name"

    override val wordFirst = "Wort zuerst"
    override val translationFirst = "Übersetzung zuerst"
    override val switchSides = "Seiten tauschen"
    override val correct = "Richtig"
    override val wrong = "Falsch"
    override val practiceFailed = "Diese Übung konnte nicht geladen werden."

    override val exitTest = "Test verlassen"
    override val testComplete = "Test abgeschlossen"
    override val checkAnswer = "Antwort prüfen"
    override val nextQuestion = "Nächste Frage"
    override val testFailed = "Dieser Test konnte nicht geladen werden."
    override val answerSaveFailed = "Die Antwort konnte nicht gespeichert werden."
    override val wellDone = "Gut gemacht!"
    override val keepPracticing = "Weiter üben"
    override val passedMessage = "Du beherrschst diese Wörter sicher. Großartig!"
    override val failedMessage = "Sieh dir die Wörter noch einmal an und versuche es erneut."
    override val incorrect = "Falsch"
    override val backToDictionary = "Zurück zum Wörterbuch"
    override val tryAgain = "Nochmal versuchen"
    override fun questionProgress(index: Int, total: Int) = "Frage $index von $total"
    override fun askMeaning(word: String) = "Was bedeutet „${word}“?"
    override fun askForm(word: String) = "Was ist „${word}“?"
    override fun correctAnswerWas(answer: String) = "Nicht ganz — die Antwort ist „${answer}“."
    override fun notEnoughWords(required: Int) =
        "Ein Test braucht mindestens $required verschiedene Wörter zur Auswahl."
    override fun scoreOf(correct: Int, total: Int) = "$correct von $total"

    override val onboardingWelcomeTitle = "Willkommen bei Verborum"
    override val onboardingLibraryTitle = "Baue deine Bibliothek auf"
    override val onboardingTestTitle = "Teste dich selbst"
    override val onboardingPracticeSwipeTitle = "Übe mit einem Wisch"
    override val onboardingPracticeFlipTitle = "Übe mit dem Umdrehen"
    override val iAmDone = "Fertig"

    override val closeKeyboard = "Tastatur schließen"
    override val space = "Leertaste"
    override val shift = "Umschalt"
    override val symbols = "Zeichen"
    override val backspace = "Rücktaste"
    override val nextField = "Nächstes Feld"
    override val keyboardUnavailable = "Keine Tastatur — wähle zuerst eine Sprache"
    override val bopomofoNote = "Bopomofo — nutze die Eingabemethode deines Systems für Zeichen."
    override val pinyinNote = "Nur Pinyin — nutze die Eingabemethode deines Systems für Zeichen."
    override fun showKeyboard(language: String) = "$language-Tastatur anzeigen"
    override fun hideKeyboard(language: String) = "$language-Tastatur ausblenden"

    override val noun = "Substantiv"
    override val verb = "Verb"
    override val adjective = "Adjektiv"
    override val adverb = "Adverb"
    override val other = "Sonstiges"
    override val freeText = "Freier Text"
    override val preposition = "Präposition"
    override val pronoun = "Pronomen"
    override val numeral = "Numerale"
    override val conjunction = "Konjunktion"
    override val interjection = "Interjektion"
    override val article = "Artikel"

    override val reading = "Lesung"
    override val plural = "Plural"
    override val feminine = "Femininum"
    override val comparative = "Komparativ"
    override val superlative = "Superlativ"
    override val present = "Präsens"
    override val past = "Präteritum"
    override val pastForm = "Vergangenheitsform"
    override val participle = "Partizip"
    override val auxiliary = "Hilfsverb"
    override val aspect = "Aspekt"
    override val root = "Wurzel"
    override val stem = "Stamm"
    override val measure = "Zähleinheit"
    override val wordClass = "Klasse"
    override val polite = "Höflichkeitsform"

    override val masculine = "maskulin"
    override val neuter = "neutrum"
    override val common = "utrum"

    override val sortNameAsc = "Name A–Z"
    override val sortNameDesc = "Name Z–A"
    override val sortNewest = "Neueste zuerst"
    override val sortOldest = "Älteste zuerst"
}
