package de.coldtea.verborum.core.localization

/** Italian. */
internal object ItalianStrings : Strings {
    override val back = "Indietro"
    override val retry = "Riprova"
    override val cancel = "Annulla"
    override val delete = "Elimina"
    override val edit = "Modifica"
    override val remove = "Rimuovi"
    override val offline = "Sei offline. Le modifiche vengono salvate localmente e sincronizzate alla riconnessione."
    override val signIn = "Accedi"
    override val createAccount = "Crea account"
    override val signInTagline = "I tuoi dizionari, su ogni dispositivo."
    override val forum = "Forum"
    override val options = "Impostazioni"
    override val comingSoon = "Prossimamente"
    override val forumFailed = "Impossibile caricare il forum."
    override val yourAccount = "Il tuo account"
    override val signOut = "Esci"
    override val signingOut = "Disconnessione…"
    override val howToUseTheApp = "Come usare l'app"
    override val appLanguage = "Lingua dell'app"
    override val appLanguageSubtitle = "La lingua in cui parla Verborum."
    override val systemLanguage = "Lingua di sistema"
    override val yourDictionaries = "I tuoi dizionari"
    override val yourDictionariesSubtitle = "Ogni coppia di lingue che stai costruendo, in un unico posto."
    override val searchDictionaries = "Cerca dizionari…"
    override val searchDictionariesAction = "Cerca dizionari"
    override val clearSearch = "Cancella ricerca"
    override val clear = "Reimposta"
    override val sortBy = "Ordina per"
    override val anyLanguage = "Tutte"
    override val moreOptions = "Altre opzioni"
    override val createDictionary = "Crea dizionario"
    override val noDictionariesMatchSearch = "Nessun dizionario corrisponde alla ricerca."
    override val noDictionaryMatchesFilters = "Nessun dizionario corrisponde a questi filtri."
    override val dictionariesFailed = "Impossibile caricare i tuoi dizionari."
    override val refreshFailed = "Aggiornamento non riuscito. Viene mostrato l'ultimo stato caricato."
    override val dictionaryDeleteFailed = "Impossibile eliminare il dizionario. È tornato nel tuo elenco."
    override val dictionary = "Dizionario"
    override val backToDictionaries = "Torna ai dizionari"
    override val test = "Test"
    override val selfPractice = "Esercizio libero"
    override val wordList = "Elenco parole"
    override val words = "Parole"
    override val addWord = "+ Aggiungi parola"
    override val deleteDictionary = "Elimina dizionario"
    override val deleteWord = "Elimina parola"
    override val noWordsYet = "Ancora nessuna parola. Aggiungi la prima qui sotto."
    override val dictionaryFailed = "Impossibile caricare questo dizionario."
    override val wordDeleteFailed = "Impossibile eliminare la parola. È tornata nell'elenco."
    override val newDictionary = "Nuovo dizionario"
    override val editDictionaryTitle = "Modifica dizionario"
    override val createDictionarySubtitle = "Dagli un nome, scegli una coppia di lingue e aggiungi etichette per filtrarlo."
    override val dictionaryName = "Nome del dizionario"
    override val dictionaryNameHint = "es. Tedesco per principianti"
    override val fromLanguage = "Lingua di partenza"
    override val toLanguage = "Lingua di arrivo"
    override val select = "Seleziona…"
    override val tags = "Etichette"
    override val tagSectionLevel = "Livello"
    override val tagSectionTopic = "Argomento"
    override val tagSectionExam = "Esame"
    override val tagSelectorExpanded = "Espanso"
    override val tagSelectorCollapsed = "Compresso"
    override val tagLevelBasic = "Base"
    override val tagLevelIntermediate = "Intermedio"
    override val tagLevelAdvanced = "Avanzato"
    override val tagTopicFoodDrink = "Cibo e bevande"
    override val tagTopicHomeAppliances = "Casa ed elettrodomestici"
    override val tagTopicClothing = "Abbigliamento"
    override val tagTopicFamily = "Famiglia"
    override val tagTopicDailyRoutine = "Routine quotidiana"
    override val tagTopicShopping = "Shopping"
    override val tagTopicMoney = "Denaro"
    override val tagTopicTravel = "Viaggi"
    override val tagTopicTransport = "Trasporti"
    override val tagTopicCarsParts = "Auto e componenti"
    override val tagTopicDirections = "Indicazioni"
    override val tagTopicCity = "Città"
    override val tagTopicNatureWeather = "Natura e meteo"
    override val tagTopicAnimals = "Animali"
    override val tagTopicPlants = "Piante"
    override val tagTopicBodyHealth = "Corpo e salute"
    override val tagTopicMedicine = "Medicina"
    override val tagTopicEmotions = "Emozioni"
    override val tagTopicWorkOffice = "Lavoro e ufficio"
    override val tagTopicBusiness = "Affari"
    override val tagTopicEducation = "Istruzione"
    override val tagTopicItTechnology = "Informatica e tecnologia"
    override val tagTopicLaw = "Diritto"
    override val tagTopicScience = "Scienza"
    override val tagTopicSports = "Sport"
    override val tagTopicMusic = "Musica"
    override val tagTopicArtFilm = "Arte e cinema"
    override val tagTopicCultureHolidays = "Cultura e feste"
    override val tagTopicNewsPolitics = "Notizie e politica"
    override val tagTopicFoodService = "Ristorazione"
    override val saveChanges = "Salva modifiche"
    override val saving = "Salvataggio…"
    override val dictionarySaveFailed = "Impossibile salvare il dizionario."
    override val dictionaryLoadFailed = "Impossibile caricare il dizionario."
    override val newWord = "Nuova parola"
    override val editWordTitle = "Modifica parola"
    override val addWordTitle = "Aggiungi parola"
    override val saveWord = "Salva parola"
    override val wordType = "Categoria grammaticale"
    override val typeOfWord = "Tipo di parola"
    override val word = "Parola"
    override val gender = "Genere"
    override val addAnotherMeaning = "+ Aggiungi un altro significato"
    override val wordSaveFailed = "Impossibile salvare la parola."
    override val wordLoadFailed = "Impossibile caricare questa parola."
    override val wordFirst = "Prima la parola"
    override val translationFirst = "Prima la traduzione"
    override val switchSides = "Inverti i lati"
    override val correct = "Corretto"
    override val wrong = "Sbagliato"
    override val practiceFailed = "Impossibile caricare questa sessione di esercizio."
    override val exitTest = "Esci dal test"
    override val testComplete = "Test completato"
    override val checkAnswer = "Verifica risposta"
    override val nextQuestion = "Domanda successiva"
    override val testFailed = "Impossibile caricare questo test."
    override val answerSaveFailed = "Impossibile salvare la risposta."
    override val wellDone = "Ottimo lavoro!"
    override val keepPracticing = "Continua a esercitarti"
    override val passedMessage = "Padroneggi bene queste parole. Complimenti!"
    override val failedMessage = "Ripassa le parole e riprova per migliorare il punteggio."
    override val incorrect = "Sbagliate"
    override val backToDictionary = "Torna al dizionario"
    override val tryAgain = "Riprova"
    override val onboardingWelcomeTitle = "Benvenuto in Verborum"
    override val onboardingLibraryTitle = "Costruisci la tua biblioteca"
    override val onboardingTestTitle = "Mettiti alla prova"
    override val onboardingPracticeSwipeTitle = "Esercitati con uno scorrimento"
    override val onboardingPracticeFlipTitle = "Esercitati girando le carte"
    override val iAmDone = "Ho finito"
    override val closeKeyboard = "Chiudi tastiera"
    override val space = "spazio"
    override val shift = "Maiusc"
    override val symbols = "Simboli"
    override val backspace = "Backspace"
    override val nextField = "Campo successivo"
    override val keyboardUnavailable = "Nessuna tastiera — scegli prima una lingua"
    override val bopomofoNote = "Bopomofo — usa il metodo di input del tuo sistema per i caratteri."
    override val pinyinNote = "Solo pinyin — usa il metodo di input del tuo sistema per i caratteri."
    override val noun = "sostantivo"
    override val verb = "verbo"
    override val adjective = "aggettivo"
    override val adverb = "avverbio"
    override val other = "altro"
    override val freeText = "testo libero"
    override val preposition = "preposizione"
    override val pronoun = "pronome"
    override val numeral = "numerale"
    override val conjunction = "congiunzione"
    override val interjection = "interiezione"
    override val article = "articolo"
    override val reading = "Lettura"
    override val plural = "Plurale"
    override val feminine = "Femminile"
    override val comparative = "Comparativo"
    override val superlative = "Superlativo"
    override val present = "Presente"
    override val past = "Passato"
    override val pastForm = "Forma passata"
    override val participle = "Participio"
    override val auxiliary = "Ausiliare"
    override val aspect = "Aspetto"
    override val root = "Radice"
    override val stem = "Tema"
    override val measure = "Classificatore"
    override val wordClass = "Classe"
    override val polite = "Forma di cortesia"
    override val masculine = "maschile"
    override val neuter = "neutro"
    override val common = "comune"
    override val sortNameAsc = "Nome A–Z"
    override val sortNameDesc = "Nome Z–A"
    override val sortNewest = "Più recenti prima"
    override val sortOldest = "Più vecchi prima"

    override fun deleteDictionaryWarning(name: String) = "«$name» e tutte le sue parole verranno eliminate."
    override fun wordCount(count: Int) = if (count == 1) "1 parola" else "$count parole"
    override fun meaningNumber(index: Int) = "Significato $index"
    override fun backTo(name: String) = "Torna a $name"
    override fun questionProgress(index: Int, total: Int) = "Domanda $index di $total"
    override fun askMeaning(word: String) = "Che cosa significa «$word»?"
    override fun askForm(word: String) = "Qual è «$word»?"
    override fun correctAnswerWas(answer: String) = "Non proprio — la risposta è «$answer»."
    override fun notEnoughWords(required: Int) =
        "Un test richiede almeno $required parole diverse fra cui scegliere."
    override fun scoreOf(correct: Int, total: Int) = "$correct su $total"
    override fun showKeyboard(language: String) = "Mostra la tastiera $language"
    override fun hideKeyboard(language: String) = "Nascondi la tastiera $language"

    override fun languageName(code: String): String = when (code.lowercase()) {
        "en" -> "Inglese"
        "de" -> "Tedesco"
        "fr" -> "Francese"
        "es" -> "Spagnolo"
        "it" -> "Italiano"
        "pt" -> "Portoghese"
        "nl" -> "Olandese"
        "lt" -> "Lituano"
        "tr" -> "Turco"
        "az" -> "Azero"
        "pl" -> "Polacco"
        "uk" -> "Ucraino"
        "ru" -> "Russo"
        "el" -> "Greco"
        "ar" -> "Arabo"
        "fa" -> "Persiano"
        "ja" -> "Giapponese"
        "zh" -> "Cinese"
        "ko" -> "Coreano"
        else -> code
    }

    override fun tagLabel(code: String): String? = when (code) {
        "basic" -> "Base"
        "intermediate" -> "Intermedio"
        "advanced" -> "Avanzato"
        "food_drink" -> "Cibo e bevande"
        "home_appliances" -> "Casa ed elettrodomestici"
        "clothing" -> "Abbigliamento"
        "family" -> "Famiglia"
        "daily_routine" -> "Routine quotidiana"
        "shopping" -> "Acquisti"
        "money" -> "Denaro"
        "travel" -> "Viaggi"
        "transport" -> "Trasporti"
        "cars_parts" -> "Auto e ricambi"
        "directions" -> "Indicazioni"
        "city" -> "Città"
        "nature_weather" -> "Natura e meteo"
        "animals" -> "Animali"
        "plants" -> "Piante"
        "body_health" -> "Corpo e salute"
        "medicine" -> "Medicina"
        "emotions" -> "Emozioni"
        "work_office" -> "Lavoro e ufficio"
        "business" -> "Affari"
        "education" -> "Istruzione"
        "it_technology" -> "Informatica e tecnologia"
        "law" -> "Diritto"
        "science" -> "Scienza"
        "sports" -> "Sport"
        "music" -> "Musica"
        "art_film" -> "Arte e cinema"
        "culture_holidays" -> "Cultura e feste"
        "news_politics" -> "Notizie e politica"
        "food_service" -> "Ristorazione"
        else -> null
    }

    override val onboardingWelcomeBody = "La tua biblioteca di vocaboli. Crea dizionari, raccogli parole e falle restare."
    override val onboardingLibraryBody = "Crea un dizionario per qualsiasi coppia di lingue, poi aggiungi le parole con la loro grammatica — articoli, plurali, forme verbali e altro."
    override val onboardingTestBody = "Fai test a scelta multipla. Ogni forma inserita diventa una domanda e le risposte corrette alzano il livello di una parola."
    override val onboardingPracticeSwipeBody = "Durante l'esercizio tocca una carta per vedere la traduzione, poi scorri a destra se la sapevi e a sinistra se no — in entrambi i casi il livello cambia."
    override val onboardingPracticeFlipBody = "Durante l'esercizio clicca una carta per girarla. Poi segnala come corretta o sbagliata — in entrambi i casi il livello della parola cambia."
}
