package de.coldtea.verborum.core.localization

/** Persian. */
internal object PersianStrings : Strings {
    override val back = "بازگشت"
    override val retry = "تلاش دوباره"
    override val cancel = "لغو"
    override val delete = "حذف"
    override val edit = "ویرایش"
    override val remove = "برداشتن"
    override val offline = "آفلاین هستید. تغییرات به‌صورت محلی ذخیره و هنگام اتصال هم‌گام می‌شوند."
    override val signIn = "ورود"
    override val createAccount = "ایجاد حساب"
    override val signInTagline = "واژه‌نامه‌های شما، روی هر دستگاه."
    override val forum = "انجمن"
    override val options = "تنظیمات"
    override val comingSoon = "به‌زودی"
    override val forumFailed = "بارگذاری انجمن ممکن نشد."
    override val yourAccount = "حساب شما"
    override val signOut = "خروج"
    override val signingOut = "در حال خروج…"
    override val howToUseTheApp = "راهنمای استفاده از برنامه"
    override val appLanguage = "زبان برنامه"
    override val appLanguageSubtitle = "زبانی که خود وربوروم با آن سخن می‌گوید."
    override val systemLanguage = "زبان سیستم"
    override val yourDictionaries = "واژه‌نامه‌های شما"
    override val yourDictionariesSubtitle = "هر جفت‌زبانی که می‌سازید، در یک جا."
    override val searchDictionaries = "جست‌وجوی واژه‌نامه‌ها…"
    override val searchDictionariesAction = "جست‌وجوی واژه‌نامه‌ها"
    override val clearSearch = "پاک کردن جست‌وجو"
    override val clear = "بازنشانی"
    override val sortBy = "مرتب‌سازی بر اساس"
    override val anyLanguage = "همه"
    override val moreOptions = "گزینه‌های بیشتر"
    override val createDictionary = "ساخت واژه‌نامه"
    override val noDictionariesMatchSearch = "هیچ واژه‌نامه‌ای با جست‌وجوی شما مطابقت ندارد."
    override val noDictionaryMatchesFilters = "هیچ واژه‌نامه‌ای با این فیلترها مطابقت ندارد."
    override val dictionariesFailed = "بارگذاری واژه‌نامه‌های شما ممکن نشد."
    override val refreshFailed = "به‌روزرسانی ممکن نشد. آنچه پیش‌تر بارگذاری شده نمایش داده می‌شود."
    override val dictionaryDeleteFailed = "حذف واژه‌نامه ممکن نشد. به فهرست شما بازگشت."
    override val dictionary = "واژه‌نامه"
    override val backToDictionaries = "بازگشت به واژه‌نامه‌ها"
    override val test = "آزمون"
    override val selfPractice = "تمرین آزاد"
    override val wordList = "فهرست واژه‌ها"
    override val words = "واژه‌ها"
    override val addWord = "+ افزودن واژه"
    override val deleteDictionary = "حذف واژه‌نامه"
    override val deleteWord = "حذف واژه"
    override val noWordsYet = "هنوز واژه‌ای نیست. اولین را در پایین بیفزایید."
    override val dictionaryFailed = "بارگذاری این واژه‌نامه ممکن نشد."
    override val wordDeleteFailed = "حذف واژه ممکن نشد. به فهرست بازگشت."
    override val newDictionary = "واژه‌نامهٔ جدید"
    override val editDictionaryTitle = "ویرایش واژه‌نامه"
    override val createDictionarySubtitle = "نامی بگذارید، جفت‌زبان را برگزینید و برای پالایش آسان برچسب بزنید."
    override val dictionaryName = "نام واژه‌نامه"
    override val dictionaryNameHint = "مثلاً مبانی آلمانی"
    override val fromLanguage = "زبان مبدأ"
    override val toLanguage = "زبان مقصد"
    override val select = "برگزینید…"
    override val tags = "برچسب‌ها"
    override val tagSectionLevel = "سطح"
    override val tagSectionTopic = "موضوع"
    override val tagSectionExam = "آزمون"
    override val tagSelectorExpanded = "باز شده"
    override val tagSelectorCollapsed = "جمع شده"
    override val tagLevelBasic = "مقدماتی"
    override val tagLevelIntermediate = "متوسط"
    override val tagLevelAdvanced = "پیشرفته"
    override val tagTopicFoodDrink = "خوراک و نوشیدنی"
    override val tagTopicHomeAppliances = "خانه و لوازم"
    override val tagTopicClothing = "پوشاک"
    override val tagTopicFamily = "خانواده"
    override val tagTopicDailyRoutine = "برنامه روزانه"
    override val tagTopicShopping = "خرید"
    override val tagTopicMoney = "پول"
    override val tagTopicTravel = "سفر"
    override val tagTopicTransport = "حمل‌ونقل"
    override val tagTopicCarsParts = "خودرو و قطعات"
    override val tagTopicDirections = "مسیرها"
    override val tagTopicCity = "شهر"
    override val tagTopicNatureWeather = "طبیعت و آب‌وهوا"
    override val tagTopicAnimals = "حیوانات"
    override val tagTopicPlants = "گیاهان"
    override val tagTopicBodyHealth = "بدن و سلامت"
    override val tagTopicMedicine = "پزشکی"
    override val tagTopicEmotions = "احساسات"
    override val tagTopicWorkOffice = "کار و اداره"
    override val tagTopicBusiness = "کسب‌وکار"
    override val tagTopicEducation = "آموزش"
    override val tagTopicItTechnology = "فناوری اطلاعات"
    override val tagTopicLaw = "حقوق"
    override val tagTopicScience = "علم"
    override val tagTopicSports = "ورزش"
    override val tagTopicMusic = "موسیقی"
    override val tagTopicArtFilm = "هنر و سینما"
    override val tagTopicCultureHolidays = "فرهنگ و اعیاد"
    override val tagTopicNewsPolitics = "اخبار و سیاست"
    override val tagTopicFoodService = "خدمات غذایی"
    override val saveChanges = "ذخیرهٔ تغییرات"
    override val saving = "در حال ذخیره…"
    override val dictionarySaveFailed = "ذخیرهٔ واژه‌نامه ممکن نشد."
    override val dictionaryLoadFailed = "بارگذاری واژه‌نامه ممکن نشد."
    override val newWord = "واژهٔ جدید"
    override val editWordTitle = "ویرایش واژه"
    override val addWordTitle = "افزودن واژه"
    override val saveWord = "ذخیرهٔ واژه"
    override val wordType = "نوع واژه"
    override val typeOfWord = "گونهٔ واژه"
    override val word = "واژه"
    override val gender = "جنس"
    override val addAnotherMeaning = "+ افزودن معنای دیگر"
    override val wordSaveFailed = "ذخیرهٔ واژه ممکن نشد."
    override val wordLoadFailed = "بارگذاری این واژه ممکن نشد."
    override val wordFirst = "نخست واژه"
    override val translationFirst = "نخست ترجمه"
    override val switchSides = "جابه‌جایی طرف‌ها"
    override val correct = "درست"
    override val wrong = "نادرست"
    override val practiceFailed = "بارگذاری این جلسهٔ تمرین ممکن نشد."
    override val exitTest = "خروج از آزمون"
    override val testComplete = "آزمون به پایان رسید"
    override val checkAnswer = "بررسی پاسخ"
    override val nextQuestion = "پرسش بعدی"
    override val testFailed = "بارگذاری این آزمون ممکن نشد."
    override val answerSaveFailed = "ذخیرهٔ پاسخ ممکن نشد."
    override val wellDone = "آفرین!"
    override val keepPracticing = "تمرین را ادامه دهید"
    override val passedMessage = "این واژه‌ها را خوب می‌دانید. کار عالی!"
    override val failedMessage = "واژه‌ها را مرور کنید و دوباره تلاش کنید تا امتیازتان بهتر شود."
    override val incorrect = "نادرست"
    override val backToDictionary = "بازگشت به واژه‌نامه"
    override val tryAgain = "تلاش دوباره"
    override val onboardingWelcomeTitle = "به وربوروم خوش آمدید"
    override val onboardingLibraryTitle = "کتابخانه‌تان را بسازید"
    override val onboardingTestTitle = "خودتان را بیازمایید"
    override val onboardingPracticeSwipeTitle = "با کشیدن تمرین کنید"
    override val onboardingPracticeFlipTitle = "با برگرداندن کارت تمرین کنید"
    override val iAmDone = "تمام شد"
    override val closeKeyboard = "بستن صفحه‌کلید"
    override val space = "فاصله"
    override val shift = "Shift"
    override val symbols = "نمادها"
    override val backspace = "پس‌بر"
    override val nextField = "فیلد بعدی"
    override val keyboardUnavailable = "صفحه‌کلیدی نیست — نخست زبانی برگزینید"
    override val bopomofoNote = "بوپوموفو — برای نویسه‌ها از روش ورودی سیستم خود استفاده کنید."
    override val pinyinNote = "فقط پین‌یین — برای نویسه‌ها از روش ورودی سیستم خود استفاده کنید."
    override val noun = "اسم"
    override val verb = "فعل"
    override val adjective = "صفت"
    override val adverb = "قید"
    override val other = "دیگر"
    override val freeText = "متن آزاد"
    override val preposition = "حرف اضافه"
    override val pronoun = "ضمیر"
    override val numeral = "عدد"
    override val conjunction = "حرف ربط"
    override val interjection = "صوت"
    override val article = "حرف تعریف"
    override val reading = "تلفظ"
    override val plural = "جمع"
    override val feminine = "مؤنث"
    override val comparative = "تفضیلی"
    override val superlative = "عالی"
    override val present = "حال"
    override val past = "گذشته"
    override val pastForm = "صورت گذشته"
    override val participle = "اسم مفعول"
    override val auxiliary = "فعل کمکی"
    override val aspect = "نمود"
    override val root = "ریشه"
    override val stem = "بن"
    override val measure = "واحد شمارش"
    override val wordClass = "رده"
    override val polite = "صورت مؤدبانه"
    override val masculine = "مذکر"
    override val neuter = "خنثی"
    override val common = "مشترک"
    override val sortNameAsc = "نام الف–ی"
    override val sortNameDesc = "نام ی–الف"
    override val sortNewest = "تازه‌ترین نخست"
    override val sortOldest = "قدیمی‌ترین نخست"

    override fun deleteDictionaryWarning(name: String) = "«$name» و همهٔ واژه‌هایش حذف خواهند شد."
    override fun wordCount(count: Int) = "$count واژه"
    override fun meaningNumber(index: Int) = "معنای $index"
    override fun backTo(name: String) = "بازگشت به $name"
    override fun questionProgress(index: Int, total: Int) = "پرسش $index از $total"
    override fun askMeaning(word: String) = "«$word» یعنی چه؟"
    override fun askForm(word: String) = "«$word» چیست؟"
    override fun correctAnswerWas(answer: String) = "نزدیک بود — پاسخ «$answer» است."
    override fun notEnoughWords(required: Int) =
        "آزمون دست‌کم به $required واژهٔ متفاوت برای انتخاب نیاز دارد."
    override fun scoreOf(correct: Int, total: Int) = "$correct از $total"
    override fun showKeyboard(language: String) = "نمایش صفحه‌کلید $language"
    override fun hideKeyboard(language: String) = "پنهان کردن صفحه‌کلید $language"

    override fun languageName(code: String): String = when (code.lowercase()) {
        "en" -> "انگلیسی"
        "de" -> "آلمانی"
        "fr" -> "فرانسوی"
        "es" -> "اسپانیایی"
        "it" -> "ایتالیایی"
        "pt" -> "پرتغالی"
        "nl" -> "هلندی"
        "lt" -> "لیتوانیایی"
        "tr" -> "ترکی"
        "az" -> "آذربایجانی"
        "pl" -> "لهستانی"
        "uk" -> "اوکراینی"
        "ru" -> "روسی"
        "el" -> "یونانی"
        "ar" -> "عربی"
        "fa" -> "فارسی"
        "ja" -> "ژاپنی"
        "zh" -> "چینی"
        "ko" -> "کره‌ای"
        else -> code
    }

    override fun tagLabel(code: String): String? = when (code) {
        "basic" -> "پایه"
        "intermediate" -> "متوسط"
        "advanced" -> "پیشرفته"
        "food_drink" -> "خوراک و نوشیدنی"
        "home_appliances" -> "خانه و لوازم"
        "clothing" -> "پوشاک"
        "family" -> "خانواده"
        "daily_routine" -> "روال روزانه"
        "shopping" -> "خرید"
        "money" -> "پول"
        "travel" -> "سفر"
        "transport" -> "حمل و نقل"
        "cars_parts" -> "خودرو و قطعات"
        "directions" -> "مسیرها"
        "city" -> "شهر"
        "nature_weather" -> "طبیعت و آب‌وهوا"
        "animals" -> "جانوران"
        "plants" -> "گیاهان"
        "body_health" -> "بدن و سلامت"
        "medicine" -> "پزشکی"
        "emotions" -> "احساسات"
        "work_office" -> "کار و دفتر"
        "business" -> "کسب‌وکار"
        "education" -> "آموزش"
        "it_technology" -> "فناوری اطلاعات"
        "law" -> "حقوق"
        "science" -> "علم"
        "sports" -> "ورزش"
        "music" -> "موسیقی"
        "art_film" -> "هنر و سینما"
        "culture_holidays" -> "فرهنگ و جشن‌ها"
        "news_politics" -> "اخبار و سیاست"
        "food_service" -> "خدمات غذایی"
        else -> null
    }

    override val onboardingWelcomeBody = "کتابخانهٔ واژگان شخصی شما. واژه‌نامه بسازید، واژه گرد آورید و آن‌ها را ماندگار کنید."
    override val onboardingLibraryBody = "برای هر جفت‌زبانی واژه‌نامه بسازید و واژه‌ها را همراه با دستورشان بیفزایید — حرف تعریف، جمع، صورت‌های فعل و بیشتر."
    override val onboardingTestBody = "آزمون چندگزینه‌ای بدهید. هر صورتی که وارد کرده‌اید پرسش خود را دارد و پاسخ درست سطح واژه را بالا می‌برد."
    override val onboardingPracticeSwipeBody = "هنگام تمرین روی کارت بزنید تا ترجمه را ببینید، سپس اگر می‌دانستید به راست و اگر نه به چپ بکشید — در هر حال سطح تغییر می‌کند."
    override val onboardingPracticeFlipBody = "هنگام تمرین روی کارت کلیک کنید تا برگردد. سپس درست یا نادرست را علامت بزنید — در هر حال سطح واژه تغییر می‌کند."
}
