package de.coldtea.verborum.core.localization

/** Polish. */
internal object PolishStrings : Strings {
    override val back = "Wstecz"
    override val retry = "Spróbuj ponownie"
    override val cancel = "Anuluj"
    override val delete = "Usuń"
    override val edit = "Edytuj"
    override val remove = "Usuń"
    override val offline = "Jesteś offline. Zmiany są zapisywane lokalnie i synchronizowane po ponownym połączeniu."
    override val signIn = "Zaloguj się"
    override val createAccount = "Załóż konto"
    override val signInTagline = "Twoje słowniki na każdym urządzeniu."
    override val forum = "Forum"
    override val options = "Ustawienia"
    override val comingSoon = "Wkrótce"
    override val forumFailed = "Nie udało się wczytać forum."
    override val yourAccount = "Twoje konto"
    override val signOut = "Wyloguj się"
    override val signingOut = "Wylogowywanie…"
    override val howToUseTheApp = "Jak korzystać z aplikacji"
    override val appLanguage = "Język aplikacji"
    override val appLanguageSubtitle = "Język, w którym mówi samo Verborum."
    override val systemLanguage = "Język systemu"
    override val yourDictionaries = "Twoje słowniki"
    override val yourDictionariesSubtitle = "Każda para językowa, którą tworzysz, w jednym miejscu."
    override val searchDictionaries = "Szukaj słowników…"
    override val searchDictionariesAction = "Szukaj słowników"
    override val clearSearch = "Wyczyść wyszukiwanie"
    override val clear = "Wyczyść"
    override val sortBy = "Sortuj według"
    override val anyLanguage = "Wszystkie"
    override val moreOptions = "Więcej opcji"
    override val createDictionary = "Utwórz słownik"
    override val noDictionariesMatchSearch = "Żaden słownik nie pasuje do wyszukiwania."
    override val noDictionaryMatchesFilters = "Żaden słownik nie pasuje do tych filtrów."
    override val dictionariesFailed = "Nie udało się wczytać Twoich słowników."
    override val refreshFailed = "Nie udało się odświeżyć. Pokazujemy ostatnio wczytane dane."
    override val dictionaryDeleteFailed = "Nie udało się usunąć słownika. Wrócił na Twoją listę."
    override val dictionary = "Słownik"
    override val backToDictionaries = "Wróć do słowników"
    override val test = "Test"
    override val selfPractice = "Samodzielna nauka"
    override val wordList = "Lista słów"
    override val words = "Słowa"
    override val addWord = "+ Dodaj słowo"
    override val deleteDictionary = "Usuń słownik"
    override val deleteWord = "Usuń słowo"
    override val noWordsYet = "Jeszcze nie ma słów. Dodaj pierwsze poniżej."
    override val dictionaryFailed = "Nie udało się wczytać tego słownika."
    override val wordDeleteFailed = "Nie udało się usunąć słowa. Wróciło na listę."
    override val newDictionary = "Nowy słownik"
    override val editDictionaryTitle = "Edytuj słownik"
    override val createDictionarySubtitle = "Nadaj mu nazwę, wybierz parę językową i otaguj, aby łatwo filtrować."
    override val dictionaryName = "Nazwa słownika"
    override val dictionaryNameHint = "np. Niemiecki dla początkujących"
    override val fromLanguage = "Język źródłowy"
    override val toLanguage = "Język docelowy"
    override val select = "Wybierz…"
    override val tags = "Tagi"
    override val tagSectionLevel = "Poziom"
    override val tagSectionTopic = "Temat"
    override val tagSectionExam = "Egzamin"
    override val tagSelectorExpanded = "Rozwinięto"
    override val tagSelectorCollapsed = "Zwinięto"
    override val tagLevelBasic = "Podstawowy"
    override val tagLevelIntermediate = "Średni"
    override val tagLevelAdvanced = "Zaawansowany"
    override val tagTopicFoodDrink = "Jedzenie i napoje"
    override val tagTopicHomeAppliances = "Dom i sprzęty"
    override val tagTopicClothing = "Odzież"
    override val tagTopicFamily = "Rodzina"
    override val tagTopicDailyRoutine = "Codzienna rutyna"
    override val tagTopicShopping = "Zakupy"
    override val tagTopicMoney = "Pieniądze"
    override val tagTopicTravel = "Podróże"
    override val tagTopicTransport = "Transport"
    override val tagTopicCarsParts = "Samochody i części"
    override val tagTopicDirections = "Wskazówki dojazdu"
    override val tagTopicCity = "Miasto"
    override val tagTopicNatureWeather = "Natura i pogoda"
    override val tagTopicAnimals = "Zwierzęta"
    override val tagTopicPlants = "Rośliny"
    override val tagTopicBodyHealth = "Ciało i zdrowie"
    override val tagTopicMedicine = "Medycyna"
    override val tagTopicEmotions = "Emocje"
    override val tagTopicWorkOffice = "Praca i biuro"
    override val tagTopicBusiness = "Biznes"
    override val tagTopicEducation = "Edukacja"
    override val tagTopicItTechnology = "IT i technologia"
    override val tagTopicLaw = "Prawo"
    override val tagTopicScience = "Nauka"
    override val tagTopicSports = "Sport"
    override val tagTopicMusic = "Muzyka"
    override val tagTopicArtFilm = "Sztuka i film"
    override val tagTopicCultureHolidays = "Kultura i święta"
    override val tagTopicNewsPolitics = "Wiadomości i polityka"
    override val tagTopicFoodService = "Gastronomia"
    override val saveChanges = "Zapisz zmiany"
    override val saving = "Zapisywanie…"
    override val dictionarySaveFailed = "Nie udało się zapisać słownika."
    override val dictionaryLoadFailed = "Nie udało się wczytać słownika."
    override val newWord = "Nowe słowo"
    override val editWordTitle = "Edytuj słowo"
    override val addWordTitle = "Dodaj słowo"
    override val saveWord = "Zapisz słowo"
    override val wordType = "Część mowy"
    override val typeOfWord = "Rodzaj słowa"
    override val word = "Słowo"
    override val gender = "Rodzaj"
    override val addAnotherMeaning = "+ Dodaj kolejne znaczenie"
    override val wordSaveFailed = "Nie udało się zapisać słowa."
    override val wordLoadFailed = "Nie udało się wczytać tego słowa."
    override val wordFirst = "Najpierw słowo"
    override val translationFirst = "Najpierw tłumaczenie"
    override val switchSides = "Zamień strony"
    override val correct = "Dobrze"
    override val wrong = "Źle"
    override val practiceFailed = "Nie udało się wczytać tej sesji nauki."
    override val exitTest = "Zakończ test"
    override val testComplete = "Test ukończony"
    override val checkAnswer = "Sprawdź odpowiedź"
    override val nextQuestion = "Następne pytanie"
    override val testFailed = "Nie udało się wczytać tego testu."
    override val answerSaveFailed = "Nie udało się zapisać odpowiedzi."
    override val wellDone = "Świetnie!"
    override val keepPracticing = "Ćwicz dalej"
    override val passedMessage = "Dobrze znasz te słowa. Świetna robota!"
    override val failedMessage = "Powtórz słowa i spróbuj ponownie, aby poprawić wynik."
    override val incorrect = "Błędne"
    override val backToDictionary = "Wróć do słownika"
    override val tryAgain = "Spróbuj ponownie"
    override val onboardingWelcomeTitle = "Witaj w Verborum"
    override val onboardingLibraryTitle = "Zbuduj swoją bibliotekę"
    override val onboardingTestTitle = "Sprawdź się"
    override val onboardingPracticeSwipeTitle = "Ćwicz przesunięciem"
    override val onboardingPracticeFlipTitle = "Ćwicz, odwracając karty"
    override val iAmDone = "Gotowe"
    override val closeKeyboard = "Zamknij klawiaturę"
    override val space = "spacja"
    override val shift = "Shift"
    override val symbols = "Symbole"
    override val backspace = "Backspace"
    override val nextField = "Następne pole"
    override val keyboardUnavailable = "Brak klawiatury — najpierw wybierz język"
    override val bopomofoNote = "Bopomofo — użyj metody wprowadzania swojego systemu, aby wpisać znaki."
    override val pinyinNote = "Tylko pinyin — użyj metody wprowadzania swojego systemu, aby wpisać znaki."
    override val noun = "rzeczownik"
    override val verb = "czasownik"
    override val adjective = "przymiotnik"
    override val adverb = "przysłówek"
    override val other = "inne"
    override val freeText = "dowolny tekst"
    override val preposition = "przyimek"
    override val pronoun = "zaimek"
    override val numeral = "liczebnik"
    override val conjunction = "spójnik"
    override val interjection = "wykrzyknik"
    override val article = "rodzajnik"
    override val reading = "Wymowa"
    override val plural = "Liczba mnoga"
    override val feminine = "Rodzaj żeński"
    override val comparative = "Stopień wyższy"
    override val superlative = "Stopień najwyższy"
    override val present = "Czas teraźniejszy"
    override val past = "Czas przeszły"
    override val pastForm = "Forma przeszła"
    override val participle = "Imiesłów"
    override val auxiliary = "Czasownik posiłkowy"
    override val aspect = "Aspekt"
    override val root = "Rdzeń"
    override val stem = "Temat"
    override val measure = "Klasyfikator"
    override val wordClass = "Klasa"
    override val polite = "Forma grzecznościowa"
    override val masculine = "męski"
    override val neuter = "nijaki"
    override val common = "wspólny"
    override val sortNameAsc = "Nazwa A–Z"
    override val sortNameDesc = "Nazwa Z–A"
    override val sortNewest = "Najnowsze najpierw"
    override val sortOldest = "Najstarsze najpierw"

    override fun deleteDictionaryWarning(name: String) = "„$name” i wszystkie jego słowa zostaną usunięte."
    override fun wordCount(count: Int) = if (count == 1) "1 słowo" else "$count słów"
    override fun meaningNumber(index: Int) = "Znaczenie $index"
    override fun backTo(name: String) = "Wróć do $name"
    override fun questionProgress(index: Int, total: Int) = "Pytanie $index z $total"
    override fun askMeaning(word: String) = "Co znaczy „$word”?"
    override fun askForm(word: String) = "Co to jest „$word”?"
    override fun correctAnswerWas(answer: String) = "Prawie — poprawna odpowiedź to „$answer”."
    override fun notEnoughWords(required: Int) =
        "Test wymaga co najmniej $required różnych słów do wyboru."
    override fun scoreOf(correct: Int, total: Int) = "$correct z $total"
    override fun showKeyboard(language: String) = "Pokaż klawiaturę: $language"
    override fun hideKeyboard(language: String) = "Ukryj klawiaturę: $language"

    override fun languageName(code: String): String = when (code.lowercase()) {
        "en" -> "Angielski"
        "de" -> "Niemiecki"
        "fr" -> "Francuski"
        "es" -> "Hiszpański"
        "it" -> "Włoski"
        "pt" -> "Portugalski"
        "nl" -> "Niderlandzki"
        "lt" -> "Litewski"
        "tr" -> "Turecki"
        "az" -> "Azerski"
        "pl" -> "Polski"
        "uk" -> "Ukraiński"
        "ru" -> "Rosyjski"
        "el" -> "Grecki"
        "ar" -> "Arabski"
        "fa" -> "Perski"
        "ja" -> "Japoński"
        "zh" -> "Chiński"
        "ko" -> "Koreański"
        else -> code
    }

    override fun tagLabel(code: String): String? = when (code) {
        "basic" -> "Podstawowy"
        "intermediate" -> "Średnio zaawansowany"
        "advanced" -> "Zaawansowany"
        "food_drink" -> "Jedzenie i napoje"
        "home_appliances" -> "Dom i sprzęty"
        "clothing" -> "Odzież"
        "family" -> "Rodzina"
        "daily_routine" -> "Codzienna rutyna"
        "shopping" -> "Zakupy"
        "money" -> "Pieniądze"
        "travel" -> "Podróże"
        "transport" -> "Transport"
        "cars_parts" -> "Samochody i części"
        "directions" -> "Wskazówki dojazdu"
        "city" -> "Miasto"
        "nature_weather" -> "Przyroda i pogoda"
        "animals" -> "Zwierzęta"
        "plants" -> "Rośliny"
        "body_health" -> "Ciało i zdrowie"
        "medicine" -> "Medycyna"
        "emotions" -> "Emocje"
        "work_office" -> "Praca i biuro"
        "business" -> "Biznes"
        "education" -> "Edukacja"
        "it_technology" -> "IT i technologia"
        "law" -> "Prawo"
        "science" -> "Nauka"
        "sports" -> "Sport"
        "music" -> "Muzyka"
        "art_film" -> "Sztuka i film"
        "culture_holidays" -> "Kultura i święta"
        "news_politics" -> "Wiadomości i polityka"
        "food_service" -> "Gastronomia"
        else -> null
    }

    override val onboardingWelcomeBody = "Twoja osobista biblioteka słownictwa. Twórz słowniki, zbieraj słowa i zapamiętuj je."
    override val onboardingLibraryBody = "Utwórz słownik dla dowolnej pary językowej, a potem dodawaj słowa wraz z gramatyką — rodzajnikami, liczbą mnogą, formami czasowników i nie tylko."
    override val onboardingTestBody = "Rozwiązuj testy wielokrotnego wyboru. Każda wprowadzona forma ma własne pytanie, a poprawne odpowiedzi podnoszą poziom słowa."
    override val onboardingPracticeSwipeBody = "Podczas nauki dotknij karty, aby zobaczyć tłumaczenie, potem przesuń w prawo, jeśli wiedziałeś, lub w lewo, jeśli nie — poziom i tak się zmieni."
    override val onboardingPracticeFlipBody = "Podczas nauki kliknij kartę, aby ją odwrócić. Następnie oznacz ją jako poprawną lub błędną — poziom słowa i tak się zmieni."
}
