package de.coldtea.verborum.core.localization

/** Spanish. */
internal object SpanishStrings : Strings {
    override val back = "Atrás"
    override val retry = "Reintentar"
    override val cancel = "Cancelar"
    override val delete = "Eliminar"
    override val edit = "Editar"
    override val remove = "Quitar"
    override val offline = "Estás sin conexión. Los cambios se guardan localmente y se sincronizan al reconectar."
    override val signIn = "Iniciar sesión"
    override val createAccount = "Crear cuenta"
    override val signInTagline = "Tus diccionarios, en todos tus dispositivos."
    override val forum = "Foro"
    override val options = "Opciones"
    override val comingSoon = "Próximamente"
    override val forumFailed = "No se pudo cargar el foro."
    override val yourAccount = "Tu cuenta"
    override val signOut = "Cerrar sesión"
    override val signingOut = "Cerrando sesión…"
    override val howToUseTheApp = "Cómo usar la aplicación"
    override val appLanguage = "Idioma de la aplicación"
    override val appLanguageSubtitle = "El idioma en el que habla Verborum."
    override val systemLanguage = "Idioma del sistema"
    override val yourDictionaries = "Tus diccionarios"
    override val yourDictionariesSubtitle = "Cada par de idiomas que estás construyendo, en un solo lugar."
    override val searchDictionaries = "Buscar diccionarios…"
    override val searchDictionariesAction = "Buscar diccionarios"
    override val clearSearch = "Borrar búsqueda"
    override val clear = "Restablecer"
    override val sortBy = "Ordenar por"
    override val anyLanguage = "Todos"
    override val moreOptions = "Más opciones"
    override val createDictionary = "Crear diccionario"
    override val noDictionariesMatchSearch = "Ningún diccionario coincide con tu búsqueda."
    override val noDictionaryMatchesFilters = "Ningún diccionario coincide con esos filtros."
    override val dictionariesFailed = "No se pudieron cargar tus diccionarios."
    override val refreshFailed = "No se pudo actualizar. Se muestra lo cargado anteriormente."
    override val dictionaryDeleteFailed = "No se pudo eliminar el diccionario. Ha vuelto a tu lista."
    override val dictionary = "Diccionario"
    override val backToDictionaries = "Volver a los diccionarios"
    override val test = "Examen"
    override val selfPractice = "Práctica libre"
    override val wordList = "Lista de palabras"
    override val words = "Palabras"
    override val addWord = "+ Añadir palabra"
    override val deleteDictionary = "Eliminar diccionario"
    override val deleteWord = "Eliminar palabra"
    override val noWordsYet = "Aún no hay palabras. Añade la primera abajo."
    override val dictionaryFailed = "No se pudo cargar este diccionario."
    override val wordDeleteFailed = "No se pudo eliminar la palabra. Ha vuelto a la lista."
    override val newDictionary = "Nuevo diccionario"
    override val editDictionaryTitle = "Editar diccionario"
    override val createDictionarySubtitle = "Ponle nombre, elige un par de idiomas y etiquétalo para filtrarlo fácilmente."
    override val dictionaryName = "Nombre del diccionario"
    override val dictionaryNameHint = "p. ej. Alemán básico"
    override val fromLanguage = "Idioma de origen"
    override val toLanguage = "Idioma de destino"
    override val select = "Seleccionar…"
    override val tags = "Etiquetas"
    override val tagSectionLevel = "Nivel"
    override val tagSectionTopic = "Tema"
    override val tagSectionExam = "Examen"
    override val tagSelectorExpanded = "Expandido"
    override val tagSelectorCollapsed = "Contraído"
    override val tagLevelBasic = "Básico"
    override val tagLevelIntermediate = "Intermedio"
    override val tagLevelAdvanced = "Avanzado"
    override val tagTopicFoodDrink = "Comida y bebida"
    override val tagTopicHomeAppliances = "Hogar y electrodomésticos"
    override val tagTopicClothing = "Ropa"
    override val tagTopicFamily = "Familia"
    override val tagTopicDailyRoutine = "Rutina diaria"
    override val tagTopicShopping = "Compras"
    override val tagTopicMoney = "Dinero"
    override val tagTopicTravel = "Viajes"
    override val tagTopicTransport = "Transporte"
    override val tagTopicCarsParts = "Coches y piezas"
    override val tagTopicDirections = "Direcciones"
    override val tagTopicCity = "Ciudad"
    override val tagTopicNatureWeather = "Naturaleza y clima"
    override val tagTopicAnimals = "Animales"
    override val tagTopicPlants = "Plantas"
    override val tagTopicBodyHealth = "Cuerpo y salud"
    override val tagTopicMedicine = "Medicina"
    override val tagTopicEmotions = "Emociones"
    override val tagTopicWorkOffice = "Trabajo y oficina"
    override val tagTopicBusiness = "Negocios"
    override val tagTopicEducation = "Educación"
    override val tagTopicItTechnology = "Informática y tecnología"
    override val tagTopicLaw = "Derecho"
    override val tagTopicScience = "Ciencia"
    override val tagTopicSports = "Deportes"
    override val tagTopicMusic = "Música"
    override val tagTopicArtFilm = "Arte y cine"
    override val tagTopicCultureHolidays = "Cultura y fiestas"
    override val tagTopicNewsPolitics = "Noticias y política"
    override val tagTopicFoodService = "Hostelería"
    override val saveChanges = "Guardar cambios"
    override val saving = "Guardando…"
    override val dictionarySaveFailed = "No se pudo guardar el diccionario."
    override val dictionaryLoadFailed = "No se pudo cargar el diccionario."
    override val newWord = "Nueva palabra"
    override val editWordTitle = "Editar palabra"
    override val addWordTitle = "Añadir palabra"
    override val saveWord = "Guardar palabra"
    override val wordType = "Categoría gramatical"
    override val typeOfWord = "Tipo de palabra"
    override val word = "Palabra"
    override val gender = "Género"
    override val addAnotherMeaning = "+ Añadir otro significado"
    override val wordSaveFailed = "No se pudo guardar la palabra."
    override val wordLoadFailed = "No se pudo cargar esta palabra."
    override val wordFirst = "Palabra primero"
    override val translationFirst = "Traducción primero"
    override val switchSides = "Intercambiar lados"
    override val correct = "Correcto"
    override val wrong = "Incorrecto"
    override val practiceFailed = "No se pudo cargar esta sesión de práctica."
    override val exitTest = "Salir del examen"
    override val testComplete = "Examen completado"
    override val checkAnswer = "Comprobar respuesta"
    override val nextQuestion = "Siguiente pregunta"
    override val testFailed = "No se pudo cargar este examen."
    override val answerSaveFailed = "No se pudo guardar la respuesta."
    override val wellDone = "¡Muy bien!"
    override val keepPracticing = "Sigue practicando"
    override val passedMessage = "Dominas bien estas palabras. ¡Buen trabajo!"
    override val failedMessage = "Repasa las palabras e inténtalo de nuevo para mejorar tu puntuación."
    override val incorrect = "Incorrecto"
    override val backToDictionary = "Volver al diccionario"
    override val tryAgain = "Intentar de nuevo"
    override val onboardingWelcomeTitle = "Bienvenido a Verborum"
    override val onboardingLibraryTitle = "Crea tu biblioteca"
    override val onboardingTestTitle = "Ponte a prueba"
    override val onboardingPracticeSwipeTitle = "Practica deslizando"
    override val onboardingPracticeFlipTitle = "Practica girando"
    override val iAmDone = "He terminado"
    override val closeKeyboard = "Cerrar teclado"
    override val space = "espacio"
    override val shift = "Mayús"
    override val symbols = "Símbolos"
    override val backspace = "Retroceso"
    override val nextField = "Campo siguiente"
    override val keyboardUnavailable = "Sin teclado — elige primero un idioma"
    override val bopomofoNote = "Bopomofo — usa el método de entrada de tu sistema para los caracteres."
    override val pinyinNote = "Solo pinyin — usa el método de entrada de tu sistema para los caracteres."
    override val noun = "sustantivo"
    override val verb = "verbo"
    override val adjective = "adjetivo"
    override val adverb = "adverbio"
    override val other = "otro"
    override val freeText = "texto libre"
    override val preposition = "preposición"
    override val pronoun = "pronombre"
    override val numeral = "numeral"
    override val conjunction = "conjunción"
    override val interjection = "interjección"
    override val article = "artículo"
    override val reading = "Lectura"
    override val plural = "Plural"
    override val feminine = "Femenino"
    override val comparative = "Comparativo"
    override val superlative = "Superlativo"
    override val present = "Presente"
    override val past = "Pasado"
    override val pastForm = "Forma de pasado"
    override val participle = "Participio"
    override val auxiliary = "Auxiliar"
    override val aspect = "Aspecto"
    override val root = "Raíz"
    override val stem = "Raíz verbal"
    override val measure = "Clasificador"
    override val wordClass = "Clase"
    override val polite = "Forma cortés"
    override val masculine = "masculino"
    override val neuter = "neutro"
    override val common = "común"
    override val sortNameAsc = "Nombre A–Z"
    override val sortNameDesc = "Nombre Z–A"
    override val sortNewest = "Más recientes primero"
    override val sortOldest = "Más antiguos primero"

    override fun deleteDictionaryWarning(name: String) = "«$name» y todas sus palabras se eliminarán."
    override fun wordCount(count: Int) = if (count == 1) "1 palabra" else "$count palabras"
    override fun meaningNumber(index: Int) = "Significado $index"
    override fun backTo(name: String) = "Volver a $name"
    override fun questionProgress(index: Int, total: Int) = "Pregunta $index de $total"
    override fun askMeaning(word: String) = "¿Qué significa «$word»?"
    override fun askForm(word: String) = "¿Cuál es «$word»?"
    override fun correctAnswerWas(answer: String) = "Casi — la respuesta es «$answer»."
    override fun notEnoughWords(required: Int) =
        "Un examen necesita al menos $required palabras distintas entre las que elegir."
    override fun scoreOf(correct: Int, total: Int) = "$correct de $total"
    override fun showKeyboard(language: String) = "Mostrar el teclado de $language"
    override fun hideKeyboard(language: String) = "Ocultar el teclado de $language"

    override fun languageName(code: String): String = when (code.lowercase()) {
        "en" -> "Inglés"
        "de" -> "Alemán"
        "fr" -> "Francés"
        "es" -> "Español"
        "it" -> "Italiano"
        "pt" -> "Portugués"
        "nl" -> "Neerlandés"
        "lt" -> "Lituano"
        "tr" -> "Turco"
        "az" -> "Azerbaiyano"
        "pl" -> "Polaco"
        "uk" -> "Ucraniano"
        "ru" -> "Ruso"
        "el" -> "Griego"
        "ar" -> "Árabe"
        "fa" -> "Persa"
        "ja" -> "Japonés"
        "zh" -> "Chino"
        "ko" -> "Coreano"
        else -> code
    }

    override fun tagLabel(code: String): String? = when (code) {
        "basic" -> "Básico"
        "intermediate" -> "Intermedio"
        "advanced" -> "Avanzado"
        "food_drink" -> "Comida y bebida"
        "home_appliances" -> "Hogar y electrodomésticos"
        "clothing" -> "Ropa"
        "family" -> "Familia"
        "daily_routine" -> "Rutina diaria"
        "shopping" -> "Compras"
        "money" -> "Dinero"
        "travel" -> "Viajes"
        "transport" -> "Transporte"
        "cars_parts" -> "Coches y piezas"
        "directions" -> "Direcciones"
        "city" -> "Ciudad"
        "nature_weather" -> "Naturaleza y clima"
        "animals" -> "Animales"
        "plants" -> "Plantas"
        "body_health" -> "Cuerpo y salud"
        "medicine" -> "Medicina"
        "emotions" -> "Emociones"
        "work_office" -> "Trabajo y oficina"
        "business" -> "Negocios"
        "education" -> "Educación"
        "it_technology" -> "Informática y tecnología"
        "law" -> "Derecho"
        "science" -> "Ciencia"
        "sports" -> "Deportes"
        "music" -> "Música"
        "art_film" -> "Arte y cine"
        "culture_holidays" -> "Cultura y fiestas"
        "news_politics" -> "Noticias y política"
        "food_service" -> "Hostelería"
        else -> null
    }

    override val onboardingWelcomeBody = "Tu biblioteca de vocabulario. Crea diccionarios, reúne palabras y haz que se queden."
    override val onboardingLibraryBody = "Crea un diccionario para cualquier par de idiomas y añade palabras junto con su gramática: artículos, plurales, formas verbales y más."
    override val onboardingTestBody = "Haz exámenes de opción múltiple. Cada forma que hayas introducido tiene su propia pregunta, y los aciertos suben el nivel de una palabra."
    override val onboardingPracticeSwipeBody = "En la práctica, toca una tarjeta para ver la traducción y desliza a la derecha si la sabías o a la izquierda si no: en ambos casos el nivel cambia."
    override val onboardingPracticeFlipBody = "En la práctica, haz clic en una tarjeta para girarla. Márcala como correcta o incorrecta: en ambos casos el nivel de la palabra cambia."
}
